#BNF+IAT 1.0 UTF-8;
!grammar control;
!slot <songRandom>;
!slot <stop>;
!slot <over>;
!slot <next>;
!slot <before>;
!slot <recite>;
!slot <poem>;
!slot <poemName>;
!slot <q104>;
!slot <q105>;
!slot <q106>;
!slot <q107>;
!slot <q108>;
!slot <q119>;
!slot <q120>;
!slot <q122>;
!slot <q123>;
!slot <q124>;
!slot <q125>;
!slot <q126>;
!slot <q127>;
!slot <q130>;
!slot <q131>;
!slot <q132>;
!slot <q133>;
!slot <q134>;
!slot <q135>;
!slot <q136>;
!slot <q137>;
!slot <q138>;
!slot <q139>;
!slot <q140>;
!slot <q141>;
!slot <q142>;
!slot <q143>;
!slot <q144>;
!slot <q145>;
!slot <q146>;
!slot <q147>;
!slot <q148>;
!slot <q149>;
!slot <q150>;
//开始
!start <controlstart>;
<controlstart>:<talk>|<playSongRandom>|<recitePoem>|<poemNext>;
//歌曲
<playSongRandom>:<songRandom>;
//背诗
<recitePoem>:[<recite>]<poemName>;
<poemNext>:<poem>[的][(<next>|<before>)];
//对话
<talk>:<stop>|<over>|<q104>|<q105>|<q106>|<q107>|<q108>|<q119>|<q120>|<q122>|<q123>|<q124>|<q125>|<q126>|<q127>|<q130>
                |<q131>|<q132>|<q133>|<q134>|<q135>|<q136>|<q137>|<q138>|<q139>|<q140>|<q141>|<q142>|<q143>|<q144>|<q145>|<q146>
                |<q147>|<q148>|<q149>|<q150>;
//内容
<stop>:我知道了!id(2)|好了!id(2)|停止!id(2)|别说了!id(2);
<over>:再见!id(3)|我走了!id(3);
<songRandom>:来首歌!id(5)|来点音乐!id(5)|唱歌!id(5)|唱首歌!id(5);
<next>:下一句!id(6)|下一句是什么!id(6);
<before>:上一句!id(7)|上一句是什么!id(7);
<recite>:背诵!id(8);
<poem>:床前明月光!id(301)|疑是地上霜!id(302)|举头望明月!id(303)|低头思故乡!id(304)|
        锄禾日当午!id(305)|汗滴禾下土!id(306)|谁知盘中餐!id(307)|粒粒皆辛苦!id(308)|
        春眠不觉晓!id(309)|处处闻啼鸟!id(310)|夜来风雨声!id(311)|花落知多少!id(312)|
        白日依山尽!id(313)|黄河入海流!id(314)|欲穷千里目!id(315)|更上一层楼!id(316)|
        离离原上草!id(317)|一岁一枯荣!id(318)|野火烧不尽!id(319)|春风吹又生!id(320)|
        秦时明月汉时关!id(321)|万里长征人未还!id(322)|但使龙城飞将在!id(323)|不教胡马度阴山!id(324)|
        朝辞白帝彩云间!id(325)|千里江陵一日还!id(326)|两岸猿声啼不住!id(327)|轻舟已过万重山!id(328)|
        月落乌啼霜满天!id(329)|江枫渔火对愁眠!id(330)|姑苏城外寒山寺!id(331)|夜半钟声到客船!id(332)|
        渭城朝雨浥轻尘!id(333)|客舍青青柳色新!id(334)|劝君更尽一杯酒!id(335)|西出阳关无故人!id(336)|
        烟笼寒水月笼沙!id(337)|夜泊秦淮近酒家!id(338)|商女不知亡国恨!id(339)|隔江犹唱后庭花!id(340);
<poemName>:静夜思!id(401)|悯农!id(402)|春晓!id(403)|登鹳雀楼!id(404)|赋得古原草送别!id(405)|草!id(405)
            |出塞!id(406)|早发白帝城!id(407)|枫桥夜泊!id(408)|送元二使安西!id(409)|泊秦淮!id(410);
<q104>:四书五经是指哪些书!id(104)|四书五经!id(104);
<q105>:中国四大名著是!id(105)|四大名著!id(105)|中国四大名著!id(105);
<q106>:中国四大书院是指!id(106)|四大书院!id(106)|中国四大书院!id(106);
<q107>:十二生肖是指!id(107)|十二生肖!id(107);
<q108>:中国四大发明是指!id(108)|四大发明!id(108)|中国四大发明!id(108);
<q119>:阅读用眼多久需要休息一下!id(119);
<q120>:五谷杂粮是指!id(120)|五谷杂粮!id(120);
<q122>:红楼梦讲什么了!id(122)|红楼梦!id(122);
<q123>:水浒传讲什么了!id(123)|水浒传!id(123);
<q124>:西游记讲什么了!id(124)|西游记!id(124);
<q125>:我该怎么付款!id(125)|我该怎么结账!id(125)|怎么结账!id(125)|怎么付款!id(125);
<q126>:你有什么功能!id(126)|你有什么特色!id(126)|你会什么!id(126)|你会干什么!id(126);
<q127>:我用支付宝付款可以不!id(127)|我用微信付款可以不!id(127)|我用手机付款可以不!id(127);
<q130>:你喜欢吃什么!id(130);
<q131>:你会唱歌吗!id(131);
<q132>:你来自哪里!id(132)|你从哪来!id(132)|你家人!id(132)|你家人是谁!id(132)|你父母!id(132)|你父母是谁!id(132)|你是!id(132)|你爸爸是谁!id(132)|你妈妈是谁!id(132);
<q133>:你会生病吗!id(133)|你会出故障么!id(133)|出问题了!id(133)|有毛病!id(133)|你会坏么!id(133)|怎么坏了!id(133)|怎么出问题了!id(133);
<q134>:你家人电话多少!id(134)|你家人联系方式!id(134);
<q135>:你叫什么名字!id(135)|你的名字!id(135);
<q136>:你多大了!id(136)|你几岁了!id(136);
<q137>:你好!id(137)|早上好!id(137)|中午好!id(137)|下午好!id(137)|晚上好!id(137);
<q138>:你好聪明!id(138)|你好厉害!id(138)|你真棒!id(138)|你真厉害!id(138);
<q139>:谢谢!id(139)|谢谢你!id(139);
<q140>:你是男是女!id(140)|你的性别!id(140)|你是男的么!id(140)|你是女的么!id(140);
<q141>:你唱的真不错!id(141)|你唱的真好!id(141)|你唱的真好听!id(141)|唱的不错!id(141)|唱的好!id(141);
<q142>:今天天气怎么样!id(142)|今天天气如何!id(142);
<q143>:今天是个好天气!id(143)|今天天气不错!id(143)|今天天气好晴朗!id(143)|今天阳光不错!id(143);
<q144>:好累呀!id(144)|好气啊!id(144)|好无聊啊!id(144)|好无奈啊!id(144)|好烦啊!id(144);
<q145>:吃了么!id(145);
<q146>:你说错了!id(146)|你又说错了!id(146)|你好笨啊!id(146);
<q147>:三国演义讲什么了!id(147)|三国演义!id(147);
<q148>:怎么不灵了!id(148)|怎么不说话了!id(148)|怎么没反应了!id(148)|没反应了!id(148);
<q149>:为什么那么任性!id(149)|怎么那么任性!id(149)|你怎么那么任性!id(149)|你为什么那么任性!id(149);
<q150>:讲个笑话吧!id(150)|我想听笑话!id(150)|来个笑话!id(150);